In [29]:
import numpy as np
import pandas as pd
from pylab import plot,show,hist,bar
%config IPCompleter.greedy=True


In [30]:
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.linear_model import SGDRegressor
from sklearn.svm import SVR
from sklearn.neural_network import MLPRegressor
from sklearn.svm import LinearSVR
from sklearn.model_selection import train_test_split

In [31]:
data = pd.read_csv("../data/train.csv",sep="\t")
#data = pd.read_csv("../data/test.csv",sep="\t")
print len(data)
#data = data.sample#(frac=0.5)
print len(data)
data.columns
data=data.drop([u'train_id', u'name', u'item_condition_id', u'category_name', u'shipping'],axis=1)
data.item_description=data.item_description.fillna('No description yet')
data.brand_name=data.brand_name.fillna('Brand Missing')

1482535
1482535


In [13]:
import nltk

nltk.download('punkt')
  
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

example_sent = ["This is a sample sentence","showing off the stop words filtration."]

stop_words = set(stopwords.words('english'))

word_tokens = word_tokenize(data.item_description)

filtered_sentence = [w for w in word_tokens if not w in stop_words]

filtered_sentence = []

for w in word_tokens:
    if w not in stop_words:
        filtered_sentence.append(w)

print(word_tokens)
print(filtered_sentence)


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\divay.jindal\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


TypeError: expected string or buffer

In [4]:
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import HashingVectorizer

In [99]:
cv=CountVectorizer(stop_words='english')
mat=cv.fit_transform( ["This is a and sample sentence","showing off the stop words filtration."])
print cv.vocabulary_
print mat.toarray()

{u'sample': 1, u'filtration': 0, u'words': 5, u'sentence': 2, u'showing': 3, u'stop': 4}
[[0 1 1 0 0 0]
 [1 0 0 1 1 1]]


In [111]:
tfcv=TfidfVectorizer()
a=tfcv.fit_transform( ["This is a and sample sentence","showing off the stop words filtration."])
print a

  (0, 9)	0.4472135955
  (0, 2)	0.4472135955
  (0, 0)	0.4472135955
  (0, 4)	0.4472135955
  (0, 5)	0.4472135955
  (1, 6)	0.408248290464
  (1, 3)	0.408248290464
  (1, 8)	0.408248290464
  (1, 7)	0.408248290464
  (1, 10)	0.408248290464
  (1, 1)	0.408248290464


In [82]:
#print cv.get_params()
print tfcv.get_feature_names()
print tfcv.vocabulary_
print a[0,:].nonzero()[1]
#print cv.stop_words_

[u'and', u'filtration', u'is', u'off', u'sample', u'sentence', u'showing', u'stop', u'the', u'this', u'words']
{u'and': 0, u'off': 3, u'sentence': 5, u'this': 9, u'is': 2, u'stop': 7, u'sample': 4, u'words': 10, u'filtration': 1, u'the': 8, u'showing': 6}
[9 2 0 4 5]


In [7]:
hv=HashingVectorizer(stop_words='english')
mat=hv.fit_transform(data.item_description)

In [16]:
print mat[0].toarray()


[[ 0.  0.  0. ...,  0.  0.  0.]]


In [13]:
print data.brand_name[400]
print data.item_description[400]

Banana Republic
Size Small Banana Republic. Citronella/gray camo. Very gently use


In [32]:
data['intersection']=map(lambda i:len(list((set(data.iloc[i].item_description.split(" ")).intersection(data.iloc[i].brand_name.split(" "))))),xrange(len(data)))

In [25]:
data['intersection1']=map(lambda i:1.0*data.iloc[i].intersection/len(data.iloc[i].item_description.split(" ")),xrange(len(data)))

In [26]:
data.intersection1.describe()

count    1.482535e+06
mean     1.606018e-02
std      4.986456e-02
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      1.000000e+00
Name: intersection1, dtype: float64

In [33]:
data[['intersection','price']].groupby(['intersection']).describe()

price                                                       
                  count       mean        std   min    25%   50%   75%     max
intersection                                                                  
0             1185493.0  25.930464  37.048908   0.0  10.00  16.0  29.0  2009.0
1              227230.0  28.347701  40.319491   0.0  11.00  18.0  31.0  2006.0
2               62243.0  36.171079  56.276743   0.0  14.00  21.0  39.0  2004.0
3                5938.0  28.973644  31.742219   0.0  12.00  20.0  33.0   800.0
4                1626.0  20.864084  19.201874   3.0  10.25  16.0  24.0   226.0
5                   5.0  21.000000   8.514693  15.0  17.00  18.0  19.0    36.0